### ISSUE TITLE
Cerebro article

### ISSUE THREAD

**Issue by BrainMaestro** [lubien/awesome-cerebro#10]
I wrote an [article](https://github.com/BrainMaestro/primer/blob/master/react/building-small-apps-with-react-cerebro.md) that walks users through creating a simple cerebro plugin. Might be useful for new developers. Is that something that could be in this repository? Or is it solely for plugins?

**Comment by lubien** [comment]
I'd love to have your article in this list! I'll be waiting for a PR.

Make sure to read the [Contribution Guidelines](CONTRIBUTING.md).

You should make a category (just like Plugins and Boilerplates) named Articles after the others. Be sure to put it on the table of contents :)

Also, for the sake of the git tree, just one commit please.

![image](https://cloud.githubusercontent.com/assets/9121359/24306713/4ef9035c-10a0-11e7-8d41-a3df97375f38.png)
