### ISSUE TITLE
Would you like to migrate this repository into the cerebro organization?

### ISSUE THREAD

**Issue by ogustavo-pereira** [lubien/awesome-cerebro#60]
we are trying to centralize the repositories that have cerebroapp relationship. Are you interested in moving this repository to the organization?

See more https://github.com/cerebroapp

**Comment by lubien** [comment]
Sure!

**Comment by ogustavo-pereira** [comment]
I sent you the request to join the organization. With that you will be able to move if you want!
Validate your email or github organization profile, as the invite will be there.

**Comment by lubien** [comment]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/9121359/187900944-773cc88a-a2b5-47c2-8bb5-7ba0b545cb57.png">

you might need to rename that one

**Comment by ogustavo-pereira** [comment]
there was a fork, I just adjusted can move. @lubien

**Comment by lubien** [comment]
We are here!
